---
apiVersion: v1
kind: Pod
metadata:
  name: livre-service
  labels:
    app: livre-service
spec:
  containers:
    - name: livre-service
      image: livre-service
      ports:
        - containerPort: 8000